// <auto-generated />
namespace TheBlogToRestart.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Whatishappeningremove300min : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Whatishappeningremove300min));
        
        string IMigrationMetadata.Id
        {
            get { return "201612080243333_Whatishappeningremove300min"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
