// <auto-generated />
namespace TheBlogToRestart.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Removed300minlength : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Removed300minlength));
        
        string IMigrationMetadata.Id
        {
            get { return "201612080240475_Removed300minlength"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
